image: gradle:jdk17-jammy

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  
stages:
  - build
  - test

build:
  tags:
    - docker
  stage: build
  script: 
    - 'chmod u+x gradle-build.sh'
    - 'chmod u+x gradlew'
    - './gradle-build.sh "$HTTP_PROXY" bootJar'
    - './gradle-build.sh "$HTTP_PROXY" hamster_client'
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test-code-job1:
  tags:
    - docker
  stage: test
  script:
    - 'chmod u+x gradle-build.sh'
    - 'chmod u+x gradlew'
    - './gradle-build.sh "$HTTP_PROXY" bootJar'
    - './gradle-build.sh "$HTTP_PROXY" hamster_client'
    - 'cd tests'
    - 'java -jar TestRunnerHamster.jar -P "java -jar ../build/libs/hamster_server.jar" -H "java -jar hamster.jar" -F hamsterdatastore.xml -C "java -jar ../build/libs/hamster_client.jar" > testresult.txt'
    - 'java -jar ResilienceRunnerHamster.jar -P "java -jar ../build/libs/hamster_server.jar" -H "java -jar hamster.jar" -F hamsterdatastore.xml -C "java -jar ../build/libs/hamster_client.jar" > resilienceresult.txt'
  artifacts:
    when: always
    paths:
      - 'tests/testresult.txt'
      - 'tests/resilienceresult.txt'
